config/routes.rb
MuniIo::Application.routes.draw do
  resources :ob_line_items

  resources :line_items

  resources :stops

  resources :directions

  resources :routes

  get "home/index"

  root 'home#index'

  resources :home do
    collection do
      get 'get_ib_items'
      get 'get_ob_items'
    end

    member do
      get 'get_ib_items'
      get 'get_ob_items'
    end
  end

end

app/models/direction.rb
class Direction < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy

	validates :r_id, :ib_id, :ib_desc, :ob_id, :ob_desc, :presence => true

private
  def direction_params
    params.require(:direction).permit(:d_id, :d_desc)
  end
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
  before_action :set_direction, only: [:show, :edit, :update, :destroy]

  # GET /directions
  # GET /directions.json
  def index
    @directions = Direction.all
  end

  # GET /directions/1
  # GET /directions/1.json
  def show
  end

  # GET /directions/new
  def new
    @direction = Direction.new
  end

  # GET /directions/1/edit
  def edit
  end

  # POST /directions
  # POST /directions.json
  def create
    @direction = Direction.new(direction_params)

    respond_to do |format|
      if @direction.save
        format.html { redirect_to @direction, notice: 'Direction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @direction }
      else
        format.html { render action: 'new' }
        format.json { render json: @direction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directions/1
  # PATCH/PUT /directions/1.json
  def update
    respond_to do |format|
      if @direction.update(direction_params)
        format.html { redirect_to @direction, notice: 'Direction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @direction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directions/1
  # DELETE /directions/1.json
  def destroy
    @direction.destroy
    respond_to do |format|
      format.html { redirect_to directions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_direction
      @direction = Direction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def direction_params
      params.require(:direction).permit(:r_id, :ib_id, :ib_desc, :ob_id, :ob_desc)
    end
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/views/directions/_form.html.erb
<%= form_for(@direction) do |f| %>
  <% if @direction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@direction.errors.count, "error") %> prohibited this direction from being saved:</h2>

      <ul>
      <% @direction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :r_id %><br>
    <%= f.text_field :r_id %>
  </div>
  <div class="field">
    <%= f.label :ib_id %><br>
    <%= f.text_field :ib_id %>
  </div>
  <div class="field">
    <%= f.label :ib_desc %><br>
    <%= f.text_field :ib_desc %>
  </div>
  <div class="field">
    <%= f.label :ob_id %><br>
    <%= f.text_field :ob_id %>
  </div>
  <div class="field">
    <%= f.label :ob_desc %><br>
    <%= f.text_field :ob_desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directions/edit.html.erb
<h1>Editing direction</h1>

<%= render 'form' %>

<%= link_to 'Show', @direction %> |
<%= link_to 'Back', directions_path %>

app/views/directions/index.html.erb
<h1>Listing directions</h1>

<table>
  <thead>
    <tr>
      <th>Route ID | </th>
      <th>Inbound ID | </th>
      <th>Inbound description | </th>
      <th>Outbound ID | </th>
      <th>Outbound description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @directions.each do |direction| %>
      <tr>
        <td><%= direction.r_id %></td>
        <td><%= direction.ib_id %></td>
        <td><%= direction.ib_desc %></td>
        <td><%= direction.ob_id %></td>
        <td><%= direction.ob_desc %></td>
        <td><%= link_to 'Show', direction %></td>
        <td><%= link_to 'Edit', edit_direction_path(direction) %></td>
        <td><%= link_to 'Destroy', direction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Direction', new_direction_path %>

app/views/directions/new.html.erb
<h1>New direction</h1>

<%= render 'form' %>

<%= link_to 'Back', directions_path %>

app/views/directions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>R ID:</strong>
  <%= @direction.r_id %>
</p>

<p>
  <strong>IB ID:</strong>
  <%= @direction.ib_id %>
</p>

<p>
  <strong>IB desc:</strong>
  <%= @direction.ib_desc %>
</p>

<p>
  <strong>OB ID:</strong>
  <%= @direction.ob_id %>
</p>

<p>
  <strong>OB desc:</strong>
  <%= @direction.ob_desc %>
</p>

<%= link_to 'Edit', edit_direction_path(@direction) %> |
<%= link_to 'Back', directions_path %>