config/routes.rb
MuniIo::Application.routes.draw do
  resources :ob_line_items

  resources :line_items

  resources :stops

  resources :directions

  resources :routes

  get "home/index"

  root 'home#index'

  resources :home do
    collection do
      get 'get_ib_items'
      get 'get_ob_items'
    end

    member do
      get 'get_ib_items'
      get 'get_ob_items'
    end
  end

end

app/models/ob_line_item.rb
class ObLineItem < ActiveRecord::Base
end

app/controllers/ob_line_items_controller.rb
class ObLineItemsController < ApplicationController
  before_action :set_ob_line_item, only: [:show, :edit, :update, :destroy]

  # GET /ob_line_items
  # GET /ob_line_items.json
  def index
    @ob_line_items = ObLineItem.all
  end

  # GET /ob_line_items/1
  # GET /ob_line_items/1.json
  def show
  end

  # GET /ob_line_items/new
  def new
    @ob_line_item = ObLineItem.new
  end

  # GET /ob_line_items/1/edit
  def edit
  end

  # POST /ob_line_items
  # POST /ob_line_items.json
  def create
    @ob_line_item = ObLineItem.new(ob_line_item_params)

    respond_to do |format|
      if @ob_line_item.save
        format.html { redirect_to @ob_line_item, notice: 'Ob line item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ob_line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @ob_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ob_line_items/1
  # PATCH/PUT /ob_line_items/1.json
  def update
    respond_to do |format|
      if @ob_line_item.update(ob_line_item_params)
        format.html { redirect_to @ob_line_item, notice: 'Ob line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ob_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ob_line_items/1
  # DELETE /ob_line_items/1.json
  def destroy
    @ob_line_item.destroy
    respond_to do |format|
      format.html { redirect_to ob_line_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ob_line_item
      @ob_line_item = ObLineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ob_line_item_params
      params.require(:ob_line_item).permit(:route_id, :direction_id, :stop_id)
    end
end

app/helpers/ob_line_items_helper.rb
module ObLineItemsHelper
end

app/views/ob_line_items/_form.html.erb
<%= form_for(@ob_line_item) do |f| %>
  <% if @ob_line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ob_line_item.errors.count, "error") %> prohibited this ob_line_item from being saved:</h2>

      <ul>
      <% @ob_line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :route_id %><br>
    <%= f.text_field :route_id %>
  </div>
  <div class="field">
    <%= f.label :direction_id %><br>
    <%= f.text_field :direction_id %>
  </div>
  <div class="field">
    <%= f.label :stop_id %><br>
    <%= f.text_field :stop_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ob_line_items/edit.html.erb
<h1>Editing ob_line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @ob_line_item %> |
<%= link_to 'Back', ob_line_items_path %>

app/views/ob_line_items/index.html.erb
<h1>Listing ob_line_items</h1>

<table>
  <thead>
    <tr>
      <th>Route</th>
      <th>Direction</th>
      <th>Stop</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ob_line_items.each do |ob_line_item| %>
      <tr>
        <td><%= ob_line_item.route_id %></td>
        <td><%= ob_line_item.direction_id %></td>
        <td><%= ob_line_item.stop_id %></td>
        <td><%= link_to 'Show', ob_line_item %></td>
        <td><%= link_to 'Edit', edit_ob_line_item_path(ob_line_item) %></td>
        <td><%= link_to 'Destroy', ob_line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ob line item', new_ob_line_item_path %>

app/views/ob_line_items/new.html.erb
<h1>New ob_line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', ob_line_items_path %>

app/views/ob_line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Route:</strong>
  <%= @ob_line_item.route_id %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @ob_line_item.direction_id %>
</p>

<p>
  <strong>Stop:</strong>
  <%= @ob_line_item.stop_id %>
</p>

<%= link_to 'Edit', edit_ob_line_item_path(@ob_line_item) %> |
<%= link_to 'Back', ob_line_items_path %>