config/routes.rb
MuniIo::Application.routes.draw do
  resources :ob_line_items

  resources :line_items

  resources :stops

  resources :directions

  resources :routes

  get "home/index"

  root 'home#index'

  resources :home do
    collection do
      get 'get_ib_items'
      get 'get_ob_items'
    end

    member do
      get 'get_ib_items'
      get 'get_ob_items'
    end
  end

end

app/models/stop.rb
class Stop < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :set_stop, only: [:show, :edit, :update, :destroy]

  # GET /stops
  # GET /stops.json
  def index
    @stops = Stop.all
  end

  # GET /stops/1
  # GET /stops/1.json
  def show
  end

  # GET /stops/new
  def new
    @stop = Stop.new
  end

  # GET /stops/1/edit
  def edit
  end

  # POST /stops
  # POST /stops.json
  def create
    @stop = Stop.new(stop_params)

    respond_to do |format|
      if @stop.save
        format.html { redirect_to @stop, notice: 'Stop was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stop }
      else
        format.html { render action: 'new' }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stops/1
  # PATCH/PUT /stops/1.json
  def update
    respond_to do |format|
      if @stop.update(stop_params)
        format.html { redirect_to @stop, notice: 'Stop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stops/1
  # DELETE /stops/1.json
  def destroy
    @stop.destroy
    respond_to do |format|
      format.html { redirect_to stops_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stop
      @stop = Stop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stop_params
      params.require(:stop).permit(:s_id, :s_desc)
    end
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/stops/_form.html.erb
<%= form_for(@stop) do |f| %>
  <% if @stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
      <% @stop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :s_id %><br>
    <%= f.text_field :s_id %>
  </div>
  <div class="field">
    <%= f.label :s_desc %><br>
    <%= f.text_field :s_desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stops/edit.html.erb
<h1>Editing stop</h1>

<%= render 'form' %>

<%= link_to 'Show', @stop %> |
<%= link_to 'Back', stops_path %>

app/views/stops/index.html.erb
<h1>Listing stops</h1>

<table>
  <thead>
    <tr>
      <th>S</th>
      <th>S desc</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stops.each do |stop| %>
      <tr>
        <td><%= stop.s_id %></td>
        <td><%= stop.s_desc %></td>
        <td><%= link_to 'Show', stop %></td>
        <td><%= link_to 'Edit', edit_stop_path(stop) %></td>
        <td><%= link_to 'Destroy', stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stop', new_stop_path %>

app/views/stops/new.html.erb
<h1>New stop</h1>

<%= render 'form' %>

<%= link_to 'Back', stops_path %>

app/views/stops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>S:</strong>
  <%= @stop.s_id %>
</p>

<p>
  <strong>S desc:</strong>
  <%= @stop.s_desc %>
</p>

<%= link_to 'Edit', edit_stop_path(@stop) %> |
<%= link_to 'Back', stops_path %>